### ISSUE TITLE
Set up Travis hook

### ISSUE THREAD

**Issue by alexpearce** [neomutt/homebrew-neomutt#1]
I've tested the formula locally with the following:

```shell
$ brew install ./Formula/neomutt.rb --with-sidebar-patch --HEAD
```

Everything goes well.

We should [set up the Travis hook](https://docs.travis-ci.com/user/getting-started/) to get nice green badge.  There's a complaint from `brew audit ./Formula/neomutt.rb` at the moment, which would cause the Travis build to fail. I'll push a fix after the hook is set up to test it.

/cc @flatcap

**Comment by flatcap** [comment]
@alexpearce 
I set my travis account to build on each commit and I see one failed build.

    https://travis-ci.org/neomutt/homebrew-neomutt/builds/122265802

I don't see any way to share the travis account, so let me know if anything needs changing.

**Comment by flatcap** [comment]
Hurrah!  I now see "build passing".

**Comment by alexpearce** [comment]
🎉 thanks!
