### ISSUE TITLE
Updater script UX

### ISSUE THREAD

**Issue by flatcap** [neomutt/homebrew-neomutt#10]
A couple of UX (user experience) thoughts:

The script uses a web API which could take some time, so a "Connection to X..." message might be in order.

If the tag doesn't exist, then the script fails quietly.
On failure, perhaps it could list the latest tags?

**Comment by alexpearce** [comment]
I think the suggestions are worth implementing.

From what I can tell, trying to parse multiple key-value pairs with sed is not going to be pretty, which would be necessary to show [the list of tags](https://developer.github.com/v3/repos/#list-tags).

We could just use another scripting language.

**Comment by flatcap** [comment]
It doesn't **need** doing, so don't bother for now.
If you _were_ to do, using `jq` (json parser) would be an alternative to using a real programming language.

**Comment by alexpearce** [comment]
Indeed, but it would introduce a dependency. I think using a better language, that comes with distros by default, would be nicer (probably Python).

**Comment by flatcap** [comment]
Agreed.
