### ISSUE TITLE
Travis: "brew audit" fails

### ISSUE THREAD

**Issue by flatcap** [neomutt/homebrew-neomutt#17]
For the last few NeoMutt releases, the HomeBrew Travis build has been failing.
The compile succeeds, but the build fails.

The command is here:
- https://travis-ci.org/neomutt/homebrew-neomutt/jobs/173368629#L1445

In the logs it suggests that: "You may have encountered a bug in the Ruby interpreter or extension libraries."

**Comment by alexpearce** [comment]
I've found a fix, implemented in the [travis-crash branch](https://github.com/neomutt/homebrew-neomutt/commit/cbf6cf3ca6e040774248ae487ab47874571c9ba7), but I'm not sure if it's sustainable. I've asked the `brew` maintainers for advice in Homebrew/brew#1450.
