### ISSUE TITLE
v1.8.0 broken

### ISSUE THREAD

**Issue by leonklingele** [neomutt/homebrew-neomutt#20]
They screwed up the v1.8.0 release: https://github.com/neomutt/neomutt/commit/b0997a4cb799433c8073229b507fc49a91d61284

**Comment by flatcap** [comment]
I've just pushed a new version: c85d98f which includes the missing semicolon.
Please can you give it a try

**Comment by leonklingele** [comment]
```
==> Checking out tag neomutt-20170225
Error: neomutt-20170225 tag should be b0997a4cb799433c8073229b507fc49a91d61284
but is actually b973854010830b8d0e8f4de5c34234d87b7eeb94
Warning: Skipping neomutt/neomutt/neomutt: most recent version 20170225 not installed
```

**Comment by flatcap** [comment]
Hmm... OK, sorry.  That's what happens when I take shortcuts.

**Comment by flatcap** [comment]
Right.  I've created a new tag 'neomutt-20170225-1' which matches that commit hash.
Please can you give it another try.

**Comment by leonklingele** [comment]
Works fine now. Thanks for the quick fix @flatcap
