### ISSUE TITLE
the --disable-nls line in the formula breaks head

### ISSUE THREAD

**Issue by lrosenman** [neomutt/homebrew-neomutt#24]
When trying to build head neomutt I ran into issues with the setlocale symbol.

I removed:

args << "--disable-nls" if build.without? "gettext"

and it builds fine.

**Comment by lrosenman** [comment]
see neomutt/neomutt#597

**Comment by guyzmo** [comment]
cf neomutt/neomutt#597

**Comment by flatcap** [comment]
Hi @lrosenman 
That line isn't in the formula any more.
Please can you give the latest Formula a test.
Thanks.
