### ISSUE TITLE
replacement of DOTLOCK_GROUP fails

### ISSUE THREAD

**Issue by andreas-bulling** [neomutt/homebrew-neomutt#27]
Hi,

when I try to install the latest version I receive the following error:

`expected replacement of /^DOTLOCK_GROUP =.*$/ with "DOTLOCK_GROUP = admin"`

Any ideas?

**Comment by flatcap** [comment]
Yes.  `mutt_dotlock` has been deprecated in the development version of NeoMut.

I've just updated the formula.  Let me know how you get on.

**Comment by andreas-bulling** [comment]
worked, thanks!
