### ISSUE TITLE
Can't build neomutt with libncurses

### ISSUE THREAD

**Issue by AndreasAZiegler** [neomutt/homebrew-neomutt#28]
As with the standard installation, ä, ö and ü as well as the Korean alphabet is not correctly displayed within neomutt (Other applications like cat, vim work), I want to link neomutt against libncursesw which I installed with Homebrew (brew install curses). For this I added "--with-curses=/usr/local/opt/ncurses to args. But I get this message:

<img width="712" alt="screen shot 2017-09-07 at 11 34 06 am" src="https://user-images.githubusercontent.com/6949508/30143393-84868e4c-93c0-11e7-99bd-c5a85f39129c.png">
 
The libraries do exist (see screenshot below):
<img width="652" alt="screen shot 2017-09-07 at 11 34 58 am" src="https://user-images.githubusercontent.com/6949508/30143428-ad173186-93c0-11e7-81c7-244785b0c5b2.png">

**Comment by benne** [comment]
I got it to compile using "--with-curses=/usr/local/opt/ncurses/lib".
However, I had the same problem as you with special characters, but even when linked correctly against ncursesw, it still showed me garbage characters.
Interestingly enough, adding --with-s-lang solved that issue.

**Comment by flatcap** [comment]
Hi.
Lots has changed since the issue was opened -- source, build, formula
In particular the build now specifically checks for ncurses**w**, since that's the main cause of character issues.

Please can you give the latest formula a try.
Thanks.
