### ISSUE TITLE
HTML Manual

### ISSUE THREAD

**Issue by flatcap** [neomutt/homebrew-neomutt#3]
You've put a TODO in the formula.
https://github.com/neomutt/homebrew-neomutt/blob/master/Formula/neomutt.rb#L9
The website manual is already out of date (slightly).  I put it there so I could link from the features' pages.

The build should already produce both a single page HTML, and a "chunked" HTML manual.
- doc/manual.html

What do you need?

**Comment by alexpearce** [comment]
Do you happen to know if `doc/manual.html` was built by mutt before, or if that's a neomutt ‘feature’?

**Comment by flatcap** [comment]
The manual was always part of Mutt.  Each NeoMutt feature adds a section to the "Optional Features" chapter.

**Comment by alexpearce** [comment]
Great, I can remove this section from the formula then (I can't find a reference to why it was added, glancing at `git log master -- Library/Formula/mutt.rb` in the main Homebrew repo).
