### ISSUE TITLE
Merge into homebrew

### ISSUE THREAD

**Issue by royger** [neomutt/homebrew-neomutt#39]
Would it be possible to have this formula added to the homebrew main repository?

- [x] Create a PR for [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core)
  Use the current Formula for Neomutt-20171215 https://github.com/Homebrew/homebrew-core/pull/24250
- [ ] Update our [Distro page](https://www.neomutt.org/distro/homebrew)
  - [ ] Part 1 for ordinary users -- Install, update from Homebrew
  - [ ] Part 2 for developers -- Existing instructions
- [ ] Update the [README](https://github.com/neomutt/homebrew-neomutt/blob/master/README.md) for this repo -- "This is for devs only, see our Distro page"
- [ ] Document the process to make a push a new release to Homebrew

<sub>(@flatcap - Added todo list)</sub>

**Comment by flatcap** [comment]
That'd be nice.

- Do you know how we'd do that?
- Do you know anyone who'd be willing to maintain that package?
  (While NeoMutt is in this local repo, it's trivial for me to update it whenever I make a release)

**Comment by jindraj** [comment]
according to brew documentation publishing is possible using pull requests. So it will maybe take some time to get merged.
What if we use neomutt/homebrew-neomutt for developers + testing and then create pull requests to homebrew/core?

**Comment by flatcap** [comment]
> So it will maybe take some time to get merged.

I imagine so the first time.

As for normal releases, it seems there's a dev script to automate the process: -- [Mutt's last release](https://github.com/Homebrew/homebrew-core/pull/23370)

> What if we use neomutt/homebrew-neomutt for developers + testing

That sounds good.
I'll add a list of jobs to the initial comment.

**Comment by fxcoudert** [comment]
Merged into Homebrew core
