### ISSUE TITLE
Brew update fails on missing dependency

### ISSUE THREAD

**Issue by kevwil** [neomutt/homebrew-neomutt#42]
I just ran `brew update && brew upgrade` to update my dev box, and I'm getting the following error:

```
neomutt/neomutt/neomutt 20180622 -> 20180716
Error: No available formula with the name "idn2" (dependency of neomutt/neomutt/neomutt)
Warning: Skipping neomutt/neomutt/neomutt: most recent version 20180716 not installed
```

Is idn2 in a special tap or something?

**Comment by flatcap** [comment]
Hi @kevwil 

Not long back Homebrew (upstream) accepted neomutt into their repo.
We recommend that everyone use that now.

'idn2' is the new version if 'idn' -- International Domain Name support.
(You can live without it)
It seems that our formula needs some more testing.

---

@ahmedelgabri 
Please could you have a look at our formula and also update the install docs
(maybe mention that our formula is for development).
https://github.com/neomutt/neomutt.github.io/blob/master/_distro/homebrew.md

Thanks.

**Comment by OkanEsen** [comment]
> Not long back Homebrew (upstream) accepted neomutt into their repo.
> We recommend that everyone use that now.

Removing the tap fixed the issue for me, thanks for the info!
