### ISSUE TITLE
Installed the latest HEAD - neovim not found

### ISSUE THREAD

**Issue by andreas-bulling** [neomutt/homebrew-neomutt#46]
Hi,

I had a working setup but after installing the latest HEAD version of neomutt I can't edit any messages in neomutt anymore but see the following error message on the console:

`sh: ../Cellar/neovim/HEAD-efaf473/bin/nvim: No such file or directory`

Any ideas what could cause this?

**UPDATE**
If I change dir to `/usr/local/Cellar` first it works. Is the path hardcoded for some reason?

**Comment by flatcap** [comment]
(I'm not a Mac user...)
I don't think this repo is used/needed any more, except for testing.

[Upstream Homebrew](https://github.com/Homebrew/homebrew-core) have merged the new release: [NeoMutt 2019-11-02](https://github.com/neomutt/neomutt/releases/tag/20191102).
Please can you give that a try.

**Comment by andreas-bulling** [comment]
still doesn't work, i.e I directly see the "message aborted" message and the editor doesn't open :(

**Comment by andreas-bulling** [comment]
I should maybe add that my neovim is also on HEAD

**Comment by jindraj** [comment]
@andreas-bulling: It seems to me like you started neomutt in some point of time, then you upgraded neovim from homebrew and since _/usr/local/bin/nvim_ is symlink pointing to _/usr/local/Cellar/neovim/HEAD-COMMIT/bin/nvim_ it doesn't exist anymore because the COMMIT hash changed. 
At least steps described above would cause this behaviour. What is your **EDITOR** env variable or neomutt **editor** config option value?

**Comment by andreas-bulling** [comment]
@jindraj Thanks a lot for your hint.

$EDITOR is `/usr/local/bin/nvim`
`/usr/local/bin/nvim -> ../Cellar/neovim/0.4.2/bin/nvim`

**Comment by jindraj** [comment]
> @jindraj Thanks a lot for your hint.
> 
> $EDITOR is `/usr/local/bin/nvim`
> `/usr/local/bin/nvim -> ../Cellar/neovim/0.4.2/bin/nvim`

did it help?

**Comment by andreas-bulling** [comment]
What do you mean helped?

`../Cellar/neovim/0.4.2/bin/nvim` exists, i.e. no problem there...

**Comment by andreas-bulling** [comment]
BTW: Upgraded neomutt (not HEAD) on another machine and hit the same problem...

**Comment by jindraj** [comment]
Does it fix itself after quitting and starting neomutt again?

**Comment by andreas-bulling** [comment]
no, unfortunately not :(

**Comment by andreas-bulling** [comment]
the latest version 20191111 fixes the problem for me. Thanks again for your help.
