### ISSUE TITLE
Tag updater is not compatible with GNU sed

### ISSUE THREAD

**Issue by alexpearce** [neomutt/homebrew-neomutt#8]
From @flatcap on PR #6:

> I get an error.
> ```
> sed: can't read /url/ s/tag => "(.)", :revision => "(.)"/tag => "neomutt-20160416", :revision => "fc12fdf30b1789ee46dbc134dd488ca22f7cb3cd"/: No such file or directory
> ```
> Gnu sed is happy with -i'' (no space) or just -i, but not -i '' (space).

I think we'll just use `-i.bak` and then delete the resulting `neomutt.rb.bak` file.

**Comment by flatcap** [comment]
That does the trick.  It's a shame it was necessary.

**Comment by alexpearce** [comment]
Indeed 😞 

Thanks for checking.
